# Generated by Django 5.2.3 on 2026-04-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('legal_name', models.CharField(blank=True, max_length=180, verbose_name='razão social')),
                ('document_number', models.CharField(blank=True, max_length=30, verbose_name='documento')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/', verbose_name='logo')),
                ('primary_color', models.CharField(default='#8A2E1E', max_length=7, verbose_name='cor primária')),
                ('secondary_color', models.CharField(default='#11212D', max_length=7, verbose_name='cor secundária')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
                'ordering': ['name'],
            },
        ),
    ]
