# Generated by Django 5.2.3 on 2026-04-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_currency',
            field=models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD'), ('EUR', 'EUR')], default='BRL', max_length=3, verbose_name='moeda padrão'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_language',
            field=models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=10, verbose_name='idioma padrão'),
        ),
    ]
