from django.urls import path

from .views import (
    IndemnityExcelExportView,
    IndemnityImportView,
    IndemnityAnalyticalReportView,
    IndemnityInsightAnalyticalReportView,
    IndemnityPdfExportView,
    IncomeItemCreateView,
    IncomeItemDeleteView,
    IncomeItemListView,
    IncomeItemUpdateView,
    IndemnityRecordCreateView,
    IndemnityRecordDeleteView,
    IndemnityRecordDetailView,
    IndemnityRecordListView,
    IndemnityRecordUpdateView,
    MeatExcelExportView,
    MeatCategoryCreateView,
    MeatCategoryDeleteView,
    MeatCategoryListView,
    MeatCategoryUpdateView,
    MeatImportView,
    MeatPdfExportView,
    MeatProductionEntryCreateView,
    MeatProductionEntryDeleteView,
    MeatProductionEntryDetailView,
    MeatProductionEntryListView,
    MeatProductionEntryUpdateView,
    ResidueCollectionCreateView,
    ResidueCollectionDeleteView,
    ResidueCollectionDetailView,
    ResidueCollectionListView,
    ResidueCollectionUpdateView,
    ResidueCategoryCreateView,
    ResidueCategoryDeleteView,
    ResidueCategoryListView,
    ResidueCategoryUpdateView,
    ResidueExcelExportView,
    ResidueImportView,
    ResiduePdfExportView,
    WeeklyIncomeEntryCreateView,
    WeeklyIncomeEntryDeleteView,
    WeeklyIncomeEntryDetailView,
    WeeklyIncomeEntryListView,
    WeeklyIncomeEntryUpdateView,
    WeeklyIncomeExcelExportView,
    WeeklyIncomeImportView,
    WeeklyIncomePdfExportView,
)


app_name = "operations"

urlpatterns = [
    path("cadastros/fontes-renda/", IncomeItemListView.as_view(), name="income-item-list"),
    path("cadastros/fontes-renda/novo/", IncomeItemCreateView.as_view(), name="income-item-create"),
    path("cadastros/fontes-renda/<int:pk>/editar/", IncomeItemUpdateView.as_view(), name="income-item-update"),
    path("cadastros/fontes-renda/<int:pk>/excluir/", IncomeItemDeleteView.as_view(), name="income-item-delete"),

    path("cadastros/carnes/", MeatCategoryListView.as_view(), name="meat-category-list"),
    path("cadastros/carnes/nova/", MeatCategoryCreateView.as_view(), name="meat-category-create"),
    path("cadastros/carnes/<int:pk>/editar/", MeatCategoryUpdateView.as_view(), name="meat-category-update"),
    path("cadastros/carnes/<int:pk>/excluir/", MeatCategoryDeleteView.as_view(), name="meat-category-delete"),

    path("cadastros/residuos/", ResidueCategoryListView.as_view(), name="residue-category-list"),
    path("cadastros/residuos/novo/", ResidueCategoryCreateView.as_view(), name="residue-category-create"),
    path("cadastros/residuos/<int:pk>/editar/", ResidueCategoryUpdateView.as_view(), name="residue-category-update"),
    path("cadastros/residuos/<int:pk>/excluir/", ResidueCategoryDeleteView.as_view(), name="residue-category-delete"),

    path("fontes-renda/", WeeklyIncomeEntryListView.as_view(), name="income-list"),
    path("fontes-renda/nova/", WeeklyIncomeEntryCreateView.as_view(), name="income-create"),
    path("fontes-renda/importar/", WeeklyIncomeImportView.as_view(), name="income-import"),
    path("fontes-renda/exportar/excel/", WeeklyIncomeExcelExportView.as_view(), name="income-export-excel"),
    path("fontes-renda/exportar/pdf/", WeeklyIncomePdfExportView.as_view(), name="income-export-pdf"),
    path("fontes-renda/<int:pk>/", WeeklyIncomeEntryDetailView.as_view(), name="income-detail"),
    path("fontes-renda/<int:pk>/editar/", WeeklyIncomeEntryUpdateView.as_view(), name="income-update"),
    path("fontes-renda/<int:pk>/excluir/", WeeklyIncomeEntryDeleteView.as_view(), name="income-delete"),

    path("carnes/", MeatProductionEntryListView.as_view(), name="meat-list"),
    path("carnes/nova/", MeatProductionEntryCreateView.as_view(), name="meat-create"),
    path("carnes/importar/", MeatImportView.as_view(), name="meat-import"),
    path("carnes/exportar/excel/", MeatExcelExportView.as_view(), name="meat-export-excel"),
    path("carnes/exportar/pdf/", MeatPdfExportView.as_view(), name="meat-export-pdf"),
    path("carnes/<int:pk>/", MeatProductionEntryDetailView.as_view(), name="meat-detail"),
    path("carnes/<int:pk>/editar/", MeatProductionEntryUpdateView.as_view(), name="meat-update"),
    path("carnes/<int:pk>/excluir/", MeatProductionEntryDeleteView.as_view(), name="meat-delete"),

    path("residuos/", ResidueCollectionListView.as_view(), name="residue-list"),
    path("residuos/novo/", ResidueCollectionCreateView.as_view(), name="residue-create"),
    path("residuos/importar/", ResidueImportView.as_view(), name="residue-import"),
    path("residuos/exportar/excel/", ResidueExcelExportView.as_view(), name="residue-export-excel"),
    path("residuos/exportar/pdf/", ResiduePdfExportView.as_view(), name="residue-export-pdf"),
    path("residuos/<int:pk>/", ResidueCollectionDetailView.as_view(), name="residue-detail"),
    path("residuos/<int:pk>/editar/", ResidueCollectionUpdateView.as_view(), name="residue-update"),
    path("residuos/<int:pk>/excluir/", ResidueCollectionDeleteView.as_view(), name="residue-delete"),

    path("indenizacoes/", IndemnityRecordListView.as_view(), name="indemnity-list"),
    path("indenizacoes/analitico/<str:status_key>/", IndemnityAnalyticalReportView.as_view(), name="indemnity-analytic-report"),
    path("indenizacoes/analitico/insight/<str:insight_key>/", IndemnityInsightAnalyticalReportView.as_view(), name="indemnity-insight-analytic-report"),
    path("indenizacoes/nova/", IndemnityRecordCreateView.as_view(), name="indemnity-create"),
    path("indenizacoes/importar/", IndemnityImportView.as_view(), name="indemnity-import"),
    path("indenizacoes/exportar/excel/", IndemnityExcelExportView.as_view(), name="indemnity-export-excel"),
    path("indenizacoes/exportar/pdf/", IndemnityPdfExportView.as_view(), name="indemnity-export-pdf"),
    path("indenizacoes/<int:pk>/", IndemnityRecordDetailView.as_view(), name="indemnity-detail"),
    path("indenizacoes/<int:pk>/editar/", IndemnityRecordUpdateView.as_view(), name="indemnity-update"),
    path("indenizacoes/<int:pk>/excluir/", IndemnityRecordDeleteView.as_view(), name="indemnity-delete"),
]
