# Generated by Django 5.2.3 on 2026-04-13 03:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120, verbose_name='ação')),
                ('module', models.CharField(max_length=80, verbose_name='módulo')),
                ('object_description', models.CharField(max_length=200, verbose_name='objeto')),
                ('details', models.TextField(blank=True, verbose_name='detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='item')),
                ('unit', models.CharField(choices=[('UNIT', 'Unidade'), ('KG', 'Quilo'), ('LITER', 'Litro'), ('SERVICE', 'Serviço')], default='UNIT', max_length=20, verbose_name='unidade')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'item de fonte de renda',
                'verbose_name_plural': 'itens de fontes de renda',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IndemnityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('occurred_on', models.DateField(verbose_name='ocorrência')),
                ('product', models.CharField(max_length=120, verbose_name='produto')),
                ('quantity_description', models.CharField(blank=True, max_length=80, verbose_name='quantidade/peso')),
                ('outgoing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor de saída')),
                ('reversal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='reversão')),
                ('owner_name', models.CharField(max_length=120, verbose_name='dono')),
                ('responsible_name', models.CharField(blank=True, max_length=120, verbose_name='responsável')),
                ('reason', models.CharField(max_length=160, verbose_name='motivo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'indenização',
                'verbose_name_plural': 'indenizações',
                'ordering': ['-occurred_on', 'product'],
            },
        ),
        migrations.CreateModel(
            name='MeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='categoria')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço por kg')),
                ('previous_price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='preço anterior')),
                ('donation_enabled', models.BooleanField(default=True, verbose_name='aceita doação')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'categoria de carne',
                'verbose_name_plural': 'categorias de carnes',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MeatProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('reference_year', models.PositiveIntegerField(verbose_name='ano')),
                ('reference_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mês')),
                ('week_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='semana')),
                ('slaughter_quantity', models.PositiveIntegerField(verbose_name='quantidade abatida')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='peso kg')),
                ('average_per_head_grams', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='média por cabeça g')),
                ('average_general_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='média geral g')),
                ('average_previous_month_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='média do mês anterior g')),
                ('donation_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='doação kg')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço por kg')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='operations.meatcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'produção de carne',
                'verbose_name_plural': 'produções de carnes',
                'ordering': ['-reference_year', '-reference_month', 'week_number', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='ResidueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='categoria')),
                ('unit', models.CharField(choices=[('KG', 'Quilo'), ('UNIT', 'Unidade'), ('LITER', 'Litro')], max_length=20, verbose_name='unidade')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='meta mensal')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitário')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'categoria de resíduo',
                'verbose_name_plural': 'categorias de resíduos',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResidueCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('collected_on', models.DateField(verbose_name='data de coleta')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='operations.residuecategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'coleta de resíduo',
                'verbose_name_plural': 'coletas de resíduos',
                'ordering': ['-collected_on', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyIncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('reference_year', models.PositiveIntegerField(verbose_name='ano')),
                ('reference_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mês')),
                ('week_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='semana')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='operations.incomeitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'lançamento semanal de renda',
                'verbose_name_plural': 'lançamentos semanais de renda',
                'ordering': ['-reference_year', '-reference_month', 'week_number', 'item__name'],
            },
        ),
    ]
