# Generated by Django 5.2.3 on 2026-04-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyincomeentry',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantidade'),
        ),
    ]
