# Generated by Django 5.2.3 on 2026-04-18 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_weeklyincomeentry_quantity'),
        ('organizations', '0002_organization_default_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndemnityLookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('field_type', models.CharField(choices=[('product', 'Produto'), ('owner', 'Dono'), ('responsible', 'Responsável'), ('reason', 'Motivo')], max_length=20, verbose_name='tipo de campo')),
                ('value', models.CharField(max_length=160, verbose_name='valor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'valor base de indenização',
                'verbose_name_plural': 'valores base de indenização',
                'ordering': ['field_type', 'value'],
                'unique_together': {('organization', 'field_type', 'value')},
            },
        ),
    ]
