# Generated by Django 5.2.3 on 2026-04-13 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='ícone')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='access.module', verbose_name='módulo pai')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='habilitado')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_accesses', to='access.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'acesso da organização',
                'verbose_name_plural': 'acessos das organizações',
            },
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='visualizar')),
                ('can_add', models.BooleanField(default=False, verbose_name='criar')),
                ('can_change', models.BooleanField(default=False, verbose_name='editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='excluir')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='access.module')),
            ],
            options={
                'verbose_name': 'acesso do usuário',
                'verbose_name_plural': 'acessos dos usuários',
            },
        ),
    ]
