# Generated by Django 5.2.3 on 2026-04-13 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmoduleaccess',
            unique_together={('organization', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleaccess',
            unique_together={('user', 'module')},
        ),
    ]
